<?php 
require_once($_SERVER['DOCUMENT_ROOT'].'/../cms_server_files/connect_database.php'); //This file contains code to login into the database
require_once($_SERVER['DOCUMENT_ROOT'].'/../cms_server_files/error_messages.php'); //This file contains error_codes
require_once($_SERVER['DOCUMENT_ROOT'].'/../cms_server_files/database_schema.php'); //This file contains schema constants of the database tables and columns
require_once($_SERVER['DOCUMENT_ROOT'].'/../cms_server_files/data_classes.php'); //This file contains data class definations



//------checking the required fields---------//
if(empty($_POST['p_id']))
{
	 printf("%s",NO_PATIENT_ID_ERROR);
	 exit; //To stop executing the php statements further
}

$checkup_record_obj=new CheckupRecord(); //Creating a new instance of the class to save passed values

$checkup_record_obj->patient_id=intval($_REQUEST['p_id']);

if(empty($_REQUEST['checkup_date']))
{
	printf("%s",NO_CHECKUP_DATE_ERROR);
	header("Location:make_new_checkup_record.php?p_id=".$_POST['p_id']);
	exit;
}
$checkup_record_obj->date_of_checkup=htmlentities($_REQUEST['checkup_date']);

if(empty($_REQUEST['counselor_id']))
{
	printf("%s",NO_COUNSELOR_ID_ERROR);
	header("Location:make_new_checkup_record.php?p_id=".$_POST['p_id']);
	exit;
}
$checkup_record_obj->counselor_id=intval($_REQUEST['counselor_id']);

if(empty($_REQUEST['checkup_type_id']))
{
	printf("%s",NO_CHECKUP_TYPE_ID_ERROR);
	header("Location:make_new_checkup_record.php?p_id=".$_POST['p_id']);
	exit;
}
$checkup_record_obj->checkup_type=intval($_REQUEST['checkup_type_id']); //Here checkup type act as checkup_type_id

if(empty($_REQUEST['no_of_sessions']))
{
	printf("%s",NO_NUM_OF_SESSIONS_ERROR);
	header("Location:make_new_checkup_record.php?p_id=".$_POST['p_id']);
	exit;
}
$checkup_record_obj->no_of_sessions=intval($_REQUEST['no_of_sessions']);

if( ! empty($_REQUEST['referred_by']))
{
	//If this field is null, database will automatically change the referred by to SELF
	$checkup_record_obj->referred_by=htmlentities($_REQUEST['referred_by']);
}

//-----------------------Optional parameters---------------------------------//
if(! empty($_REQUEST['checkup_remarks']))
{
	$checkup_record_obj->remarks=htmlentities($_REQUEST['checkup_remarks']);
}

//Following lines will execute only if the required fields are received

//--------------------------------Connecting to the database------------------------------------------//

@$database=connect_database(); //this funtion is defined in another file(connect_database); '@' prevents the php engine to print any error generated after executing this statement

if(mysqli_connect_errno())//This function returns a non zero value if there was any error in connection
{
	 printf("%s",DATABASE_CONNECION_ERROR);
	 exit; //To stop executing the php statements further
}

//The following lines will run only if the connection to database server is successful
$insertQuery="INSERT INTO `".CHECKUP_RECORD_TABLE."`(`patient_id`, `date_of_checkup`, `counselor_id`, `checkup_type_id`, `no_of_sessions`, `remarks`,`referred_by`)"
			." VALUES(?,?,?,?,?,?,?);";

$statement=$database->prepare($insertQuery); //Prepare a prepared-statement to avoid sql injection attacks
$statement->bind_param('dsdddss',
	 $checkup_record_obj->patient_id,
     $checkup_record_obj->date_of_checkup,
     $checkup_record_obj->counselor_id,
     $checkup_record_obj->checkup_type,
     $checkup_record_obj->no_of_sessions,
	 $checkup_record_obj->remarks,
	 $checkup_record_obj->referred_by); //Binding the ? to it's value; s-string 

if(!$statement->execute()) //Actually send the data to the MySQL server
{
	//true means that insert query was successful, false means unsuccessful
	printf('%s',DATABASE_INSERT_ERROR); //printf() gives advantage of specifying format specifier to prevent malicious code unlike echo
	exit; //Exit executing php further
}
//Following lines will execute only if database insertion was successful
printf("%s","Insert Successful");
if(! $database->insert_id==0) //insert_id is the id generated by an insert/update query of the autoincrement column in the database
{
	header("Location:get_checkup_sessions.php?cr_id=".$database->insert_id);
}
else
{
	//insert_id returns 0 if there is no insert or update query or if the table doesnot have autoincrement column
	header("Location:patient_details.php?p_id=".$checkup_record_obj->patient_id);
}

?>